nelmio_api_doc:
    documentation:
        info:
            title: 'Inspectors API'
            version: '1.0.0'
        areas:
            default:
                path_patterns:
                    - ^/api(?!/doc)
