controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_doc:
    path: /api/doc
    methods: GET
    controller: nelmio_api_doc.controller.swagger_ui

api_docs:
    path: /api/docs
    methods: GET
    controller: nelmio_api_doc.controller.swagger_ui

api_doc_json:
    path: /api/doc.json
    methods: GET
    controller: nelmio_api_doc.controller.swagger
